//AUTH ACTIONS
export const REGISTER_OK = 'REGISTER_OK'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_FAILURE = 'AUTH_FAILURE'
export const LOGIN_OK = 'LOGIN_OK'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT = 'LOGOUT'
export const CLEAR_FAILURES = 'CLEAR_FAILURES'

//PROJECT ACTIONS
export const NEW_PROJECT = 'NEW_PROJECT'
export const FETCH_PROJECTS = 'FETCH_PROJECTS'
export const DELETE_PROJECT = 'DELETE_PROJECT'

//TICKET ACTIONS
